import type { MetadataRoute } from "next";

/**
 * PWA Web App Manifest — generated by Next.js metadata route.
 * NOTE: For a full installable PWA experience the owner should add proper
 * PNG icons (192×192 and 512×512) to /public/ and reference them here.
 * The favicon.ico is a placeholder entry only.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Blu Café",
    short_name: "Blu",
    description: "Gestión de negocio para Blu Café",
    start_url: "/",
    display: "standalone",
    background_color: "#f8fafc",
    theme_color: "#0369a1",
    icons: [
      {
        src: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
    ],
  };
}
