-- Seed: fill in specific descriptions for the migrated activities so each task
-- is unambiguous for staff. Idempotent: only sets description where it is still
-- NULL, so manual edits made in the UI are never overwritten.

UPDATE public.activities SET description = CASE title
  -- Apertura
  WHEN 'Dejar listo ambiente exterior (barrer, trapear, mesas y flores)'
    THEN 'Barre y trapea el patio, limpia y alinea mesas y sillas, y renueva el agua de las flores.'
  WHEN 'Verificar stock de bebidas y jarabes'
    THEN 'Revisa leche, jarabes, café en grano y descartables; reporta lo que falte antes de abrir.'
  WHEN 'Calibrar espresso'
    THEN 'Ajusta molienda y dosis hasta lograr un shot equilibrado (25-30 s) antes del primer pedido.'
  WHEN 'Prepara área de trabajo (maquina de café, licuadora, accesorios, etc.)'
    THEN 'Enciende y purga la máquina; ubica pitchers, tamper y accesorios limpios y a la mano.'
  WHEN 'Limpiar vitrina de postres (por dentro y por fuera)'
    THEN 'Limpia los vidrios por dentro y por fuera y ordena los postres bien presentados.'
  WHEN 'Barrer, trapear y limpiar zona interior (incluye baño)'
    THEN 'Barre y trapea el salón interior y el baño; verifica que el baño tenga papel y jabón.'
  WHEN 'Limpiar mesas y sillas interiores'
    THEN 'Desinfecta mesas y sillas del salón y coloca individuales y servilletas.'
  WHEN 'Preparar área de trabajo (tablas, cuchillos, etc.)'
    THEN 'Alista tablas, cuchillos y utensilios limpios; sanitiza la superficie de trabajo.'
  WHEN 'Revisión y reporte de stock de comidas saladas'
    THEN 'Revisa insumos de salados y reporta faltantes antes del servicio.'
  -- Jornada
  WHEN 'Preparar jarabes e insumos de bebidas'
    THEN 'Prepara y rotula los jarabes e insumos del día para las bebidas.'
  WHEN 'Porcionar insumos de bebidas'
    THEN 'Porciona leche, fruta y toppings en las cantidades del servicio.'
  WHEN 'Preparar bebidas según pedidos'
    THEN 'Prepara las bebidas siguiendo la receta y el estándar de presentación.'
  WHEN 'Apoyar en atención de mesas (alto flujo)'
    THEN 'Apoya en tomar pedidos y atender mesas cuando el flujo es alto.'
  WHEN 'Apoyar en cobro y emisión de boletas (alto flujo)'
    THEN 'Apoya en el cobro y la emisión de boletas cuando el flujo es alto.'
  WHEN 'Recolectar vajilla sucia de mesas (alto flujo)'
    THEN 'Retira la vajilla sucia de las mesas y llévala a lavado sin dejar acumulación.'
  WHEN 'Preparar comidas saladas del menú'
    THEN 'Prepara los platos salados del menú según receta y estándar.'
  WHEN 'Emplatar comidas saladas y dulces'
    THEN 'Emplata salados y dulces cuidando la presentación y la limpieza del plato.'
  WHEN 'Cobrar cuentas y emitir boletas'
    THEN 'Cobra las cuentas y emite la boleta correspondiente a cada pedido.'
  WHEN 'Lavar menaje usado'
    THEN 'Lava el menaje usado durante el servicio para mantener la rotación.'
  -- Cierre
  WHEN 'Limpiar máquina de café y licuadora'
    THEN 'Purga y limpia grupo, vaporizador y bandeja de la máquina; lava y seca pitchers y el vaso de la licuadora.'
  WHEN 'Limpiar y ordenar barra'
    THEN 'Limpia la barra, guarda tazas y accesorios, y cierra y ordena los jarabes y botellas del mueble.'
  WHEN 'Barres y trapear cocina'
    THEN 'Barre y trapea el piso de la cocina y la trastienda al cerrar.'
  WHEN 'Limpieza profunda refrigeradora'
    THEN 'Vacía, limpia y desinfecta la refrigeradora; descarta lo vencido y ordena por fecha.'
  WHEN 'Revisión inventario general'
    THEN 'Cuenta el inventario general y registra faltantes para la compra de la semana.'
  WHEN 'Limpieza profunda cocina'
    THEN 'Limpieza profunda de cocina: campana, hornillas, superficies y pisos.'
  WHEN 'Revisión insumos perecibles'
    THEN 'Revisa fechas de perecibles, aplica PEPS y descarta lo que no esté apto.'
  WHEN 'Limpiar área de cocina y refrigeradora'
    THEN 'Limpia superficies y hornillas de la cocina y el frente de la refrigeradora; retira restos y grasa.'
  WHEN 'Lavar y ordenar menaje'
    THEN 'Lava todo el menaje y guárdalo seco en su lugar; deja las mesas de trabajo despejadas (sin platos ni tazas encima).'
  WHEN 'Barrer residuos de comida de la zona exterior'
    THEN 'Recoge y barre los residuos de comida del patio y saca la basura al cerrar.'
  WHEN 'Guardar postres, individuales y cojines'
    THEN 'Guarda los postres en refrigeración y recoge individuales y cojines al cerrar.'
  ELSE description
END
WHERE description IS NULL;
